version: "3.9"
services:
        db:
                image: postgres
                environment:
                        POSTGRES_USER: youtube
                        POSTGRES_DB: youtube
                        POSTGRES_PASSWORD: youtube123
                ports:
                        - "5432:5432"
        
        web:
                build: .
                command: python manage.py runserver 0.0.0.0:8080
                volumes: 
                        - .:/code/
                ports: 
                        - "8080:80"
                depends_on:
                        - db